spring.application.name=webapp

#connect postgres
spring.datasource.url=jdbc:postgresql://postgres_container:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true